#!/bin/bash

#
# https://www.mankier.com/1/ffmpeg-utils#Syntax-Time_duration
#
if [[ $# -ne 2 ]] 
  then
    echo
    echo "create a silent file (pause), durating specified milliseconds"
    echo "usage: $0 <audiofile> <milliseconds>"
    echo
    exit
fi

CODEC='mp3'
BITRATE=24000

ffmpeg -y -f lavfi -i anullsrc=r=$BITRATE:cl=mono -t $2ms -acodec $CODEC $1
