#!/bin/bash 
echo
echo "Full init of local git repo, forcing a first commit to a remote repo."

if [ $# -eq 0 ]
  then
    echo "usage: $0 <commit message>"
    exit
fi

# store the current origin remote url
GIT_URL=`git remote get-url origin`

#set the commit message to command line parameters
COMMIT_MESSAGE=$@

rm -rf .git/

git init
git remote add origin $GIT_URL  
echo

#echo
#echo "Commit changes"

#echo "purge sessions/SESSIONSDB.json"
#echo -e "{}" > sessions/SESSIONSDB.json
#echo

# add all files and commit
git add .
git commit -m "$COMMIT_MESSAGE"

#echo "Reset local git repo"
echo
git push origin master -f

sleep 5
echo
npm publish

